BookLibrary/BookLibrary/Controllers/BookController.cs
using BLL.Contracts;
using BookLibrary.Models;
using Identity.Infrastructure;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookLibrary.Controllers
{
    public class BookController : Controller
    {
        public BookController()
        {
            _onlineLibrary = IoC.Factory.GetOnlineLibrary();
        }

        private IOnlineLibrary _onlineLibrary;

        // GET: Book
        public ActionResult Index(int? page, int? size)
        {
            var userId = Request.IsAuthenticated ? Convert.ToInt32(User.Identity.GetUserId()) : -1;
            int selectedPage = page == null ? 1 : page.Value > 0 ? page.Value : 1;
            int selectedSize = size == null ? 25 : size.Value > 0 ? size.Value : 25;
            PageInfo pageInfo = new PageInfo
            {
                PageSize = selectedSize,
                PageNumber = selectedPage
            };
            pageInfo.PageCount = _onlineLibrary.CountPagesBooks(pageInfo.PageSize);

            ViewBag.CurrentCategory = "";
            ViewBag.PageInfo = pageInfo;

            var books = _onlineLibrary.GetBooks(selectedPage - 1, pageInfo.PageSize);
            var categories = _onlineLibrary.GetCategories(0, int.MaxValue);
            ViewBag.Categories = categories.Select(x => new Category
            {
                Id = x.Id,
                Title = x.Title,
                Description = x.Description
            });

            var models = new List<Book>();
            foreach (var item in books)
            {
                var model = new Book()
                {
                    Id = item.Id,
                    Title = item.Title,
                    Description = item.Description,
                    Link = item.Link,
                    CategoryId = item.CategoryId,
                    Category = _onlineLibrary.GetCategoryById(item.CategoryId),
                    FavouriteBook = _onlineLibrary.GetFavouriteBookByUserIdAndBookId(item.Id, userId),
                    Logo = item.Logo ?? "https://files.selar.co/product-images/2017/products/demo/preorder-physical-product-selar.co-59d1e525c3a96.jpg",
                    Author = item.Author,
                    CommentCount = _onlineLibrary.CountCommentsByBook(item.Id),
                    CreationDate = item.CreationDate
                };
                models.Add(model);
            }

            return View(models);
        }

        // POST: Search
        [HttpPost]
        public ActionResult Search(Search search, int? page, int? size)
        {
            if (ModelState.IsValid)
            {
                if (string.IsNullOrWhiteSpace(search.Query))
                {
                    search.Query = "";
                }

                var userId = Request.IsAuthenticated ? Convert.ToInt32(User.Identity.GetUserId()) : -1;

                int selectedPage = page == null ? 1 : page.Value > 0 ? page.Value : 1;
                int selectedSize = size == null ? 25 : size.Value > 0 ? size.Value : 25;
                PageInfo pageInfo = new PageInfo
                {
                    PageSize = selectedSize,
                    PageNumber = selectedPage
                };
                pageInfo.PageCount = _onlineLibrary.CountPagesForSearch(search.Query, 0, pageInfo.PageSize);

                ViewBag.CurrentCategory = "";
                ViewBag.PageInfo = pageInfo;

                var books = _onlineLibrary.SearchBooks(search.Query, 0, selectedPage - 1, pageInfo.PageSize);
                var categories = _onlineLibrary.GetCategories(0, int.MaxValue);
                ViewBag.Categories = categories.Select(x => new Category
                {
                    Id = x.Id,
                    Title = x.Title,
                    Description = x.Description
                });

                var models = new List<Book>();
                foreach (var item in books)
                {
                    var model = new Book()
                    {
                        Id = item.Id,
                        Title = item.Title,
                        Description = item.Description,
                        Link = item.Link,
                        CategoryId = item.CategoryId,
                        Category = _onlineLibrary.GetCategoryById(item.CategoryId),
                        FavouriteBook = _onlineLibrary.GetFavouriteBookByUserIdAndBookId(item.Id, userId),
                        Logo = item.Logo ?? "https://files.selar.co/product-images/2017/products/demo/preorder-physical-product-selar.co-59d1e525c3a96.jpg",
                        Author = item.Author,
                        CommentCount = _onlineLibrary.CountCommentsByBook(item.Id),
                        CreationDate = item.CreationDate
                    };
                    models.Add(model);
                }

                return PartialView("BookList", models);
            }
            return PartialView("BookList", null);
        }

        // GET: Category
        public ActionResult Category(int id)
        {
            var userId = Request.IsAuthenticated ? Convert.ToInt32(User.Identity.GetUserId()) : -1;
            var books = _onlineLibrary.GetBooksFromCategory(id, 0, int.MaxValue);

            var categories = _onlineLibrary.GetCategories(0, int.MaxValue);
            ViewBag.Categories = categories.Select(x => new Category
            {
                Id = x.Id,
                Title = x.Title,
                Description = x.Description
            });

            ViewBag.CurrentCategory = "in " + _onlineLibrary.GetCategoryById(id).Title;

            var models = new List<Book>();
            foreach (var book in books)
            {
                var model = new Book()
                {
                    Id = book.Id,
                    Title = book.Title,
                    Description = book.Description,
                    Link = book.Link,
                    CategoryId = book.CategoryId,
                    Category = _onlineLibrary.GetCategoryById(book.CategoryId),
                    FavouriteBook = _onlineLibrary.GetFavouriteBookByUserIdAndBookId(book.Id, userId),
                    Logo = book.Logo,
                    CreationDate = book.CreationDate,
                    CommentCount = 0,
                    Author = book.Author,
                };
                models.Add(model);
            }

            return View("Index", models);
        }

        // GET: Create
        [Authorize(Roles = "Administrators,Moderators")]
        public ActionResult Create()
        {
            ViewBag.Categories = _onlineLibrary.GetCategories(0, int.MaxValue);
            return View();
        }

        // POST: Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrators,Moderators")]
        public ActionResult Create(Book model, HttpPostedFileBase upload, HttpPostedFileBase logo)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            if (upload != null)
            {
                string fileName = System.IO.Path.GetFileName(upload.FileName);

                fileName = $"{Guid.NewGuid().ToString()}_{fileName}";

                var path = $"~/App_Data/{fileName}";

                var link = $"/Book/Download?file={fileName}";

                upload.SaveAs(Server.MapPath(path));
                model.Link = link;
            }

            if (logo != null)
            {
                string fileName = System.IO.Path.GetFileName(logo.FileName);

                fileName = $"{Guid.NewGuid().ToString()}_{fileName}";

                var path = $"~/App_Data/{fileName}";

                var link = $"/Book/Download?file={fileName}";

                logo.SaveAs(Server.MapPath(path));
                model.Logo = link;
            }

            model.CreationDate = DateTime.Now;
            var result = _onlineLibrary.CreateBook(model);

            if (result == null)
            {
                return View(model);
            }

            return RedirectToAction("Index");
        }

        // GET: Download
        public ActionResult Download(string file)
        {
            string path = Server.MapPath($"~/App_Data/{file}");

            if (!System.IO.File.Exists(path))
            {
                return Redirect("~/Error/NotFound");
            }

            string fileType = "application/pdf";

            string fileName = "file";

            return File(path, fileType, fileName);
        }


        // GET: Edit
        [Authorize(Roles = "Administrators,Moderators")]
        public ActionResult Edit(int id)
        {
            var book = _onlineLibrary.GetBookById(id);

            ViewBag.Categories = _onlineLibrary.GetCategories(0, int.MaxValue);

            var model = new Book()
            {
                Id = book.Id,
                Title = book.Title,
                Description = book.Description,
                CategoryId = book.CategoryId,
                Link = book.Link,
                Category = _onlineLibrary.GetCategoryById(book.CategoryId),
                Logo = book.Logo,
                CreationDate = book.CreationDate,
                CommentCount = 0,
                Author = book.Author,
            };

            return View(model);
        }

        // POST: Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrators,Moderators")]
        public ActionResult Edit(Book model)
        {
            ViewBag.Categories = _onlineLibrary.GetCategories(0, int.MaxValue);
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var result = _onlineLibrary.UpdateBook(model);

            if (!result)
            {
                return View(model);
            }

BookLibrary/BookLibrary/Controllers/CategoryController.cs
using BLL.Contracts;
using BookLibrary.Models;
using System.Collections.Generic;
using System.Web.Mvc;

namespace BookLibrary.Controllers
{
    public class CategoryController : Controller
    {
        public CategoryController()
        {
            _onlineLibrary = IoC.Factory.GetOnlineLibrary();
        }

        private IOnlineLibrary _onlineLibrary;

        // GET: Category
        public ActionResult Index()
        {
            var categories = _onlineLibrary.GetCategories(0, int.MaxValue);
            var models = new List<Category>();
            foreach (var category in categories)
            {
                var model = new Category()
                {
                    Id = category.Id,
                    Title = category.Title,
                    Description = category.Description
                };
                models.Add(model);
            }

            return View(models);
        }

        // GET: Create
        [Authorize(Roles = "Administrators,Moderators")]
        public ActionResult Create()
        {
            return View(new Category());
        }

        // POST: Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrators,Moderators")]
        public ActionResult Create(Category model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var result = _onlineLibrary.CreateCategory(model);
            
            if (result == null)
            {
                return View(model);
            }

            return RedirectToAction("Index");
        }

        // GET: Edit
        [Authorize(Roles = "Administrators,Moderators")]
        public ActionResult Edit(int id)
        {
            var category = _onlineLibrary.GetCategoryById(id);

            var model = new Category()
            {
                Id = category.Id,
                Title = category.Title,
                Description = category.Description
            };

            return View(model);
        }

        // POST: Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrators,Moderators")]
        public ActionResult Edit(Category model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var result = _onlineLibrary.UpdateCategory(model);

            if (!result)
            {
                return View(model);
            }

            return RedirectToAction("Index");
        }

        // GET: Delete
        [Authorize(Roles = "Administrators,Moderators")]
        public ActionResult Delete(int id)
        {
            var result = _onlineLibrary.DeleteCategory(id);

            return RedirectToAction("Index");
        }
    }
}

BookLibrary/BookLibrary/Controllers/CommentController.cs
using BLL.Contracts;
using BookLibrary.Models;
using Identity.Infrastructure;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Web;
using System.Web.Mvc;

namespace BookLibrary.Controllers
{
    public class CommentController : Controller
    {
        public CommentController()
        {
            _onlineLibrary = IoC.Factory.GetOnlineLibrary();
        }

        private IOnlineLibrary _onlineLibrary;

        // POST: Comment
        [Authorize]
        [HttpPost]
        public ActionResult Create([Bind(Include = "BookId,Text")]Comment comment)
        {
            if (!ModelState.IsValid)
            {
                return Content("<div></div>");
            }

            var userId = Request.IsAuthenticated ? Convert.ToInt32(User.Identity.GetUserId()) : -1;
            var userManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();

            comment.UserName = userManager.FindById(userId).UserName;
            comment.CreationDate = DateTime.Now;
            comment.UserId = userId;

            var created = _onlineLibrary.CreateComment(comment);

            var model = new Comment
            {
                BookId = created.BookId,
                UserId = created.UserId,
                Id = created.Id,
                CreationDate = created.CreationDate,
                Text = created.Text,
                UserName = comment.UserName,
            };

            return PartialView("~/Views/Shared/_Comment.cshtml", model);
        }

        // POST: Comment
        [Authorize]
        [HttpPost]
        public ActionResult Edit([Bind(Include = "Id,BookId,Text,CreationDate,UserId")]Comment comment)
        {
            if (!ModelState.IsValid)
            {
                return Content("<div></div>");
            }

            var userId = Request.IsAuthenticated ? Convert.ToInt32(User.Identity.GetUserId()) : -1;
            var userManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();

            comment.UserName = userManager.FindById(userId).UserName;
            comment.UserId = userId;

            var isUpdated = _onlineLibrary.UpdateComment(comment);

            var model = new Comment
            {
                BookId = comment.BookId,
                UserId = comment.UserId,
                Id = comment.Id,
                CreationDate = comment.CreationDate,
                Text = comment.Text,
                UserName = comment.UserName,
            };

            return PartialView("~/Views/Shared/_Comment.cshtml", model);
        }

        // POST: Comment
        [HttpPost]
        [Authorize]
        public ActionResult Delete(int id)
        {
            var userId = Request.IsAuthenticated ? Convert.ToInt32(User.Identity.GetUserId()) : -1;

            var comment = _onlineLibrary.GetComment(id);

            if (comment != null && comment.UserId == userId)
            {
                _onlineLibrary.DeleteComment(id);
            }

            return Content("<div></div>");
        }
    }
}

BookLibrary/BookLibrary/Controllers/FavouriteBookController.cs
using BLL.Contracts;
using BookLibrary.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookLibrary.Controllers
{
    [Authorize]
    public class FavouriteBookController : Controller
    {
        public FavouriteBookController()
        {
            _onlineLibrary = IoC.Factory.GetOnlineLibrary();
        }

        private IOnlineLibrary _onlineLibrary;

        // GET: Add FavouriteBook
        public ActionResult Add(int? id, string redirectTo)
        {
            if (id.HasValue && Request.IsAuthenticated)
            {
                var userId = Convert.ToInt32(User.Identity.GetUserId());
                var book = _onlineLibrary.GetBookById(id.Value);

                if (book != null)
                {
                    _onlineLibrary.CreateFavouriteBook(new FavouriteBook { BookId = book.Id, UserId = userId });
                }
            }

            return Redirect(redirectTo);
        }

        // GET: Delete FavouriteBook
        public ActionResult Delete(int? id, string redirectTo)
        {
            if (id.HasValue)
                _onlineLibrary.DeleteFavouriteBook(id.Value);

            return Redirect(redirectTo);
        }
    }
}

BookLibrary/BookLibrary/Views/Book/Book.cshtml
@model BookLibrary.Models.Book

@{
    ViewBag.Title = Model.Title;
}

@Styles.Render("~/Content/css/fa")

<div style="margin-top: 25px;">
    <div class="row">
        <div class="media col-md-12">
            <a class="pull-left" href="#">
                <img width="200" height="300" class="media-object" src="@Url.Content(Model.Logo)">
            </a>
            <div class="media-body" style="padding-left: 10px;">
                <h4 class="media-heading">@Html.DisplayFor(modelItem => Model.Title)</h4>
                <h5 class="media-heading" style="font-weight: bold">@Html.DisplayFor(modelItem => Model.Author)</h5>
                <br />
                <p>
                    @Model.Description
                </p>
                <p>
                    Category:
                    @Html.ActionLink(Model.Category.Title, "Category", "Book", new { id = Model.Category.Id.ToString() }, new { @class = "" })
                </p>
                @if (Request.IsAuthenticated)
                {
                    if (Model.FavouriteBook != null)
                    {
                        @Html.ActionLink("Dislike", "Delete", "FavouriteBook", new { id = Model.FavouriteBook.Id.ToString(), redirectTo = "/Book/" }, new { id = Model.FavouriteBook.Id, @class = "btn btn-danger" })
                    }
                    else
                    {
                        @Html.ActionLink("Like!", "Add", "FavouriteBook", new { id = Model.Id.ToString(), redirectTo = "/Book/" }, new { id = Model.Id, @class = "btn btn-success" })
                    }
                }
                <ul class="list-inline list-unstyled">
                    <li><a href="@Html.DisplayFor(modelItem => Model.Link)" class="btn btn-link">Download</a></li>
                    <li>|</li>
                    <li><span><i class="glyphicon glyphicon-calendar"></i> @Model.CreationDate.ToShortDateString() </span></li>
                    <li>|</li>
                    <li><span><i class="glyphicon glyphicon-comment"></i> @Model.CommentCount</span></li>
                    @if (Request.IsAuthenticated && (User.IsInRole("Administrators") || User.IsInRole("Moderators")))
                    {
                        <li>|</li>
                        <li>@Html.ActionLink("Edit", "Edit", "Book", new { id = Model.Id.ToString() }, new { @class = "" })</li>
                        <li>|</li>
                        <li>@Html.ActionLink("Delete", "Delete", "Book", new { id = Model.Id.ToString() }, new { @class = "" })</li>
                    }
                </ul>
            </div>
            <div class="clear"></div>
        </div>
    </div>
</div>
<p style="margin-top: 15px;">
    @Html.ActionLink("Back to List", "Index")
</p>

@{
    var Comments = (IEnumerable<BookLibrary.Models.Comment>)ViewBag.Comments;
}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3 class="page-header">Comments</h3>
            <section class="comment-list" id="results">
                @foreach (var comment in Comments)
                {
                    @Html.Partial("_Comment", comment)
                }


            </section>
            @if (User.Identity.IsAuthenticated)
            {
                <div class="col-md-5" style="">
                    <h4>Leave your comment</h4>
                    @using (Ajax.BeginForm("Create", "Comment", null, new AjaxOptions
                    {
                        UpdateTargetId = "results",
                        InsertionMode = InsertionMode.InsertAfter,
                        OnComplete = "resetForm()"
                    }, new { @id = "comment-form" }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.Hidden("BookId", Model.Id)
                        @Html.TextArea("Text", new { @class = "form-control", @id = "comment-textarea", @style = "max-width: 100% !important;", @placeholder = "Enter your comment here... Minimum is 2 chars." })
                        <input type="submit" value="Post" id="comment-submit" class="btn btn-success" style="margin-top: 10px;" />
                    }
                </div>

                <script defer>
                    window.onload = function () {
                        $('#comment-textarea').keydown(function (e) {
                            if (e.ctrlKey && e.keyCode == 13) {
                                console.log("pressed");
                                $('#comment-form').trigger('submit');
                                $('#comment-textarea').val("");
                            }
                        })
                    };
                </script>
            }
        </div>
    </div>
</div>

<script>
    function resetForm() {
        $("#comment-form").trigger("reset");
        $('#comment-textarea').val("");
    }

    function remove(id) {
        $.ajax({
            url: "/Comment/Delete?id=" + id,
            type: "POST",
            success: function () {
                var comments = $(".comment");
                var ids = comments.find(".comment-id");

                for (var i = 0; i < ids.length; i++) {
                    if (ids[i].innerHTML == id) {
                        comments[i].remove();
                    }
                }
            }
        });

        
    }
</script>

BookLibrary/BookLibrary/Views/Book/BookList.cshtml
@model IEnumerable<BookLibrary.Models.Book>

@using PagedList.Mvc;

@{
    ViewBag.Title = "Books";
    var pageInfo = (PagedList.IPagedList)ViewBag.PageInfo;
}


@if (Model?.FirstOrDefault() == null)
{
    <h3>Empty list</h3>
    <p>There is no books...</p>
}
else
{
    foreach (var item in Model)
    {
    <div class="row">
        <div class="media col-md-12">
            <a class="pull-left" href="@Url.Content(@Url.Action("Book", "Book", new { id = item.Id }, "http"))">
                <img width="200" height="300" class="media-object" src="@Url.Content(item.Logo)">
            </a>
            <div class="media-body" style="padding-left: 10px;">
                <a href="@Url.Content(@Url.Action("Book", "Book", new { id = item.Id }, "http"))">
                    <h4 class="media-heading">@Html.DisplayFor(modelItem => item.Title)</h4>
                </a>
                <h5 class="media-heading" style="font-weight: bold">@Html.DisplayFor(modelItem => item.Author)</h5>
                <br />
                <p>
                    @item.Description.Substring(0, 200)...
                </p>
                <p>
                    Category:
                    @Html.ActionLink(item.Category.Title, "Category", "Book", new { id = item.Category.Id.ToString() }, new { @class = "" })
                </p>
                @if (Request.IsAuthenticated)
                {
                    if (item.FavouriteBook != null)
                    {
                        @Html.ActionLink("Dislike", "Delete", "FavouriteBook", new { id = item.FavouriteBook.Id.ToString(), redirectTo = "/Book/" }, new { id = item.FavouriteBook.Id, @class = "btn btn-danger" })
                    }
                    else
                    {
                        @Html.ActionLink("Like!", "Add", "FavouriteBook", new { id = item.Id.ToString(), redirectTo = "/Book/" }, new { id = item.Id, @class = "btn btn-success" })
                    }
                }
                <ul class="list-inline list-unstyled">
                    <li><a href="@Html.DisplayFor(modelItem => item.Link)" class="btn btn-link">Download</a></li>
                    <li>|</li>
                    <li><span><i class="glyphicon glyphicon-calendar"></i> @item.CreationDate.ToShortDateString() </span></li>
                    <li>|</li>
                    <li><span><i class="glyphicon glyphicon-comment"></i> @item.CommentCount</span></li>
                    @if (Request.IsAuthenticated && (User.IsInRole("Administrators") || User.IsInRole("Moderators")))
                    {
                        <li>|</li>
                        <li>@Html.ActionLink("Edit", "Edit", "Book", new { id = item.Id.ToString() }, new { @class = "" })</li>
                        <li>|</li>
                        <li>@Html.ActionLink("Delete", "Delete", "Book", new { id = item.Id.ToString() }, new { @class = "" })</li>
                    }
                </ul>
            </div>
            <div class="clear"></div>
        </div>
    </div>
    <hr />
    }
}


@if (pageInfo != null)
{
    <br />
    <span>Page @(pageInfo.PageCount < pageInfo.PageNumber ? 0 : pageInfo.PageNumber) of @pageInfo.PageCount</span>

    @Html.PagedListPager(pageInfo, page => Url.Action("Index", new { page }))
}

BookLibrary/BookLibrary/Views/Book/Create.cshtml
@model BookLibrary.Models.Book

@{
    ViewBag.Title = "Create Book";
}

@using (Html.BeginForm("Create", "Book", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h2>New Book</h2>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.Title, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Author, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Author, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Author, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("file", "File", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" class="upload valid" id="upload" name="upload" />
            <br />
            <button id="resetFile" class="btn" type="button">Don't use file</button><br>
        </div>
    </div>

    <div class="form-group">
        @Html.Label("logo", "Logo", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" class="upload valid" id="logo" name="logo" />
            <br>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Link, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Link, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Link, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.CategoryId,
                               ((IEnumerable<BLL.Contracts.DTOs.ICategory>)ViewBag.Categories).Select(x => new SelectListItem()
                               {
                                   Value = x.Id.ToString(),
                                   Text = x.Title
                               }), new { @class = "form-control" })
            @*@Html.EditorFor(model => model.CategoryId, new { htmlAttributes = new { @class = "form-control" } })*@
            @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script>
    var upload = document.getElementById("upload");
    upload.onchange = function () {
        var link = document.getElementById("Link");
        link.value = "Using file...";
    };

    var reset = document.getElementById("resetFile");
    reset.onclick = function () {
        var link = document.getElementById("Link");
        this.value = "";
        if (link.value == "Using file...")
            link.value = "";
    };
</script>

BookLibrary/BookLibrary/Views/Book/Index.cshtml
@model IEnumerable<BookLibrary.Models.Book>

@using PagedList.Mvc;

@{
    ViewBag.Title = "Books";
    var pageInfo = (PagedList.IPagedList)ViewBag.PageInfo;
}

@Styles.Render("~/Content/css/PagedList")

@Html.Partial("~/Views/Shared/_Search.cshtml", new BookLibrary.Models.Search())

<div class="container">
    <div class="col-md-9">
        <div>
            <h2 class="pull-left">Books @ViewBag.CurrentCategory</h2>
            <p class="pull-right">
                @if (Request.IsAuthenticated && (User.IsInRole("Administrators") || User.IsInRole("Moderators")))
                {
                    @Html.ActionLink("+", "Create", "Book", null, new { @class = "btn btn-success new" })
                }
            </p>
            <div class="clear"></div>
        </div>
        <hr />
        <div class="results" id="results">
            @Html.Partial("BookList", Model)
        </div>
    </div>
    <div class="col-md-3">
        <h3 class="text-center">Categories</h3>
        <ul class="nav nav-stacked">
            <li>@Html.ActionLink("All", "Index", "Book", null, new { @class = "btn btn-link" })</li>
            @foreach (var item in (IEnumerable<BookLibrary.Models.Category>)ViewBag.Categories)
            {
                <li>@Html.ActionLink(item.Title, "Category", "Book", new { id = item.Id }, new { @class = "btn btn-link" })</li>
            }
        </ul>
    </div>
</div>