BookLibrary/BookLibrary/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BookLibrary.Models;
using Identity.Infrastructure;
using Microsoft.AspNet.Identity.Owin;

namespace BookLibrary.Controllers
{
    [Authorize(Roles = "Administrators")]
    public class AdminController : Controller
    {
        public AdminController()
        {

        }

        private ApplicationUserManager UserManager
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
        }
    }
}

BookLibrary/BookLibrary/Controllers/RoleAdminController.cs
using BookLibrary.Models.Roles;
using Identity.Infrastructure;
using Identity.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace BookLibrary.Controllers
{
    [Authorize(Roles = "Administrators")]
    public class RoleAdminController : Controller
    {

        public ActionResult Index()
        {
            return View(RoleManager.Roles);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create([Required]string name)
        {
            if (ModelState.IsValid)
            {
                IdentityResult result = await RoleManager.CreateAsync(new CustomRole(name));

                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    AddErrorsFromResult(result);
                }
            }
            return View(name);
        }

        [HttpPost]
        public async Task<ActionResult> Delete(string id)
        {
            CustomRole role = await RoleManager.FindByIdAsync(Convert.ToInt32(id));
            if (role != null)
            {
                IdentityResult result = await RoleManager.DeleteAsync(role);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return View("Index", "Error");
                }
            }
            else
            {
                return View("Index", "Error");
            }
        }

        public async Task<ActionResult> Edit(string id)
        {
            CustomRole role = await RoleManager.FindByIdAsync(Convert.ToInt32(id));
            int[] memberIDs = role.Users.Select(x => x.UserId).ToArray();

            IEnumerable<ApplicationUser> members
                = UserManager.Users.Where(x => memberIDs.Any(y => y == x.Id));

            IEnumerable<ApplicationUser> nonMembers = UserManager.Users.Except(members);

            return View(new RoleEditVM
            {
                Role = role,
                Members = members,
                NonMembers = nonMembers
            });
        }

        [HttpPost]
        public async Task<ActionResult> Edit(RoleModificationVM model)
        {
            IdentityResult result;
            if (ModelState.IsValid)
            {
                foreach (string userId in model.IdsToAdd ?? new string[] { })
                {
                    result = await UserManager.AddToRoleAsync(Convert.ToInt32(userId), model.RoleName);

                    if (!result.Succeeded)
                    {
                        return View("Index", "Error");
                    }
                }
                foreach (string userId in model.IdsToDelete ?? new string[] { })
                {
                    result = await UserManager.RemoveFromRoleAsync(Convert.ToInt32(userId),
                    model.RoleName);

                    if (!result.Succeeded)
                    {
                        return View("Index", "Error");
                    }
                }
                return RedirectToAction("Index");

            }
            return View("Error", new string[] { "Роль не найдена" });
        }

        private void AddErrorsFromResult(IdentityResult result)
        {
            foreach (string error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }
        }

        private ApplicationUserManager UserManager
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
        }

        private ApplicationRoleManager RoleManager
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<ApplicationRoleManager>();
            }
        }
    }
}

BookLibrary/BookLibrary/Views/Admin/Index.cshtml
@{
    ViewBag.Title = "Admin - Test List";
}

<br />
<div class="row">
    <div class="col-md-4">
        <p>
            @Html.ActionLink("Users", "Users", "Admin", null, new { @class = "btn btn-default" })
        </p>
    </div>
</div>

BookLibrary/BookLibrary/Views/Admin/Users.cshtml
@using Identity.Models
@model IEnumerable<ApplicationUser>

@{
    ViewBag.Title = "ASP.NET Identity";
}

<br />
<div class="row">
    <div class="col-md-4">
        <p>
            @Html.ActionLink("Roles", "Index", "RoleAdmin", null, new { @class = "btn btn-default" })
        </p>
    </div>
</div>
<div class="panel panel-primary">
    <div class="panel-heading">
        Users
    </div>
    <table class="table table-striped">
        <tr>
            <th>Id</th>
            <th>Login</th>
            <th>Email</th>
        </tr>
        @if (Model.Count() == 0)
        {
            <tr>
                <td colspan="3" class="text-center">User list is empty.</td>
            </tr>
        }
        else
        {
            foreach (ApplicationUser user in Model)
            {
                <tr>
                    <td>@user.Id</td>
                    <td>@user.UserName</td>
                    <td>@user.Email</td>
                </tr>
            }
        }
    </table>
</div>